"""One-off generator for per-skill audit notes. Run from repo: python _build_skills.py"""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parent


def npx_install(repo: str, skill: str) -> str:
    """Install command as shown on skills.sh (`npx skills add` + GitHub repo + `--skill`)."""
    return f"npx skills add https://github.com/{repo} --skill {skill}"


def sec_urls(skill_page: str) -> tuple[str, str, str]:
    base = skill_page.rstrip("/")
    return (
        f"{base}/security/agent-trust-hub",
        f"{base}/security/socket",
        f"{base}/security/snyk",
    )


def render(
    *,
    title: str,
    skill_page: str | None,
    repo: tuple[str, str] | None,
    session: str,
    weekly: str | None,
    signal: str,
    summary: str,
    install_bash: str | None,
    hub: str,
    socket: str,
    snyk: str,
) -> str:
    meta_lines: list[str] = []
    if skill_page:
        meta_lines.append(f"**Skill page (skills.sh):** [{title}]({skill_page})")
    if repo:
        meta_lines.append(f"**Upstream repository:** [{repo[0]}]({repo[1]})")
    meta_lines.append(f"**Session match:** {session}")
    if weekly:
        meta_lines.append(f"**Weekly installs (public):** `{weekly}`")
    meta_block = "\n\n".join(meta_lines)

    callout = {
        "Success": "> [!success] Overall security signal\n> Snapshot: **Success** — clean pass across all three auditors at extraction time.\n\n",
        "Review": "> [!warning] Overall security signal\n> Snapshot: **Review** — at least one auditor reported a warning; manual review recommended.\n\n",
        "Danger": "> [!danger] Overall security signal\n> Snapshot: **Danger** — at least one failure or high-risk signal; review before installing.\n\n",
        "Info": "> [!info] Directory entry\n> This is the public skills directory, not an installable skill package.\n\n",
    }[signal]

    if install_bash is None:
        install_section = (
            "### INSTALLATION\n\n"
            "---\n\n"
            "Not applicable — browse and discover skills on [skills.sh](https://skills.sh/)."
        )
    else:
        install_section = (
            "### INSTALLATION\n\n"
            "---\n\n"
            "```bash\n"
            f"{install_bash}\n"
            "```"
        )

    hub_l, sock_l, snyk_l = ("", "", "")
    base = skill_page.rstrip("/") if skill_page else ""
    has_audit_pages = bool(base and base != "https://skills.sh" and hub not in ("—", "N/A"))
    if has_audit_pages:
        u1, u2, u3 = sec_urls(skill_page or "")
        hub_l = f" [Details]({u1})"
        sock_l = f" [Details]({u2})"
        snyk_l = f" [Details]({u3})"

    audits_table = "\n".join(
        [
            "| Audit | Result |",
            "| :--- | :--- |",
            f"| Gen Agent Trust Hub | **{hub}**{hub_l} |",
            f"| Socket | **{socket}**{sock_l} |",
            f"| Snyk | **{snyk}**{snyk_l} |",
        ]
    )

    snapshot = (
        "> [!note] About this snapshot\n"
        "> Public `skills.sh` security snapshot dated **2026-04-10** in the parent audit. "
        "Install commands mirror the skills.sh **Installation** block (`npx skills add …`). "
        "This is **not** a manual source-code audit of the repository."
    )

    fm_title = title.replace('"', '\\"')
    parts = [
        "---",
        f'title: "{fm_title}"',
        "tags:",
        "  - skills",
        "  - security-audit",
        "  - onetab",
        "audited: 2026-04-10",
        "---",
        "",
        f"# {title}",
        "",
        snapshot,
        "",
        meta_block,
        "",
        callout.rstrip(),
        "",
        "> [!abstract] Summary",
        f"> {summary}",
        "",
        install_section,
        "",
        "### SECURITY AUDITS",
        "",
        "---",
        "",
        "Order: **Gen Agent Trust Hub** → **Socket** → **Snyk**.",
        "",
        audits_table,
        "",
    ]
    return "\n".join(parts)


RECORDS: list[dict] = [
    {
        "file_slug": "vercel-react-best-practices",
        "title": "vercel-react-best-practices",
        "skill_page": "https://skills.sh/vercel-labs/agent-skills/vercel-react-best-practices",
        "repo": ("vercel-labs/agent-skills", "https://github.com/vercel-labs/agent-skills"),
        "session": "Yes",
        "weekly": "301.0K",
        "signal": "Success",
        "summary": "React and Next.js performance optimisation guidance from Vercel Engineering.",
        "install_bash": npx_install("vercel-labs/agent-skills", "vercel-react-best-practices"),
        "hub": "PASS",
        "socket": "PASS",
        "snyk": "PASS",
    },
    {
        "file_slug": "frontend-design-anthropics",
        "title": "frontend-design (anthropics/skills)",
        "skill_page": "https://skills.sh/anthropics/skills/frontend-design",
        "repo": ("anthropics/skills", "https://github.com/anthropics/skills"),
        "session": "Yes",
        "weekly": "272.5K",
        "signal": "Success",
        "summary": "Frontend design skill from Anthropic’s skills collection (distinct from the pbakaus/impeccable variant; same CLI name — pick one upstream).",
        "install_bash": npx_install("anthropics/skills", "frontend-design"),
        "hub": "PASS",
        "socket": "PASS",
        "snyk": "PASS",
    },
    {
        "file_slug": "web-design-guidelines",
        "title": "web-design-guidelines",
        "skill_page": "https://skills.sh/vercel-labs/agent-skills/web-design-guidelines",
        "repo": ("vercel-labs/agent-skills", "https://github.com/vercel-labs/agent-skills"),
        "session": "Yes",
        "weekly": "241.9K",
        "signal": "Review",
        "summary": "Audit UI code against Vercel’s Web Interface Guidelines for design and accessibility compliance.",
        "install_bash": npx_install("vercel-labs/agent-skills", "web-design-guidelines"),
        "hub": "PASS",
        "socket": "PASS",
        "snyk": "WARN",
    },
    {
        "file_slug": "agent-browser",
        "title": "agent-browser",
        "skill_page": "https://skills.sh/vercel-labs/agent-browser/agent-browser",
        "repo": ("vercel-labs/agent-browser", "https://github.com/vercel-labs/agent-browser"),
        "session": "No",
        "weekly": "171.7K",
        "signal": "Danger",
        "summary": "Fast, persistent browser automation with session continuity across sequential agent commands.",
        "install_bash": npx_install("vercel-labs/agent-browser", "agent-browser"),
        "hub": "PASS",
        "socket": "WARN",
        "snyk": "FAIL",
    },
    {
        "file_slug": "vercel-composition-patterns",
        "title": "vercel-composition-patterns",
        "skill_page": "https://skills.sh/vercel-labs/agent-skills/vercel-composition-patterns",
        "repo": ("vercel-labs/agent-skills", "https://github.com/vercel-labs/agent-skills"),
        "session": "Yes",
        "weekly": "124.9K",
        "signal": "Success",
        "summary": "React composition patterns that scale (compound components, providers, flexible APIs).",
        "install_bash": npx_install("vercel-labs/agent-skills", "vercel-composition-patterns"),
        "hub": "PASS",
        "socket": "PASS",
        "snyk": "PASS",
    },
    {
        "file_slug": "ui-ux-pro-max",
        "title": "ui-ux-pro-max",
        "skill_page": "https://skills.sh/nextlevelbuilder/ui-ux-pro-max-skill/ui-ux-pro-max",
        "repo": ("nextlevelbuilder/ui-ux-pro-max-skill", "https://github.com/nextlevelbuilder/ui-ux-pro-max-skill"),
        "session": "Yes",
        "weekly": "108.5K",
        "signal": "Danger",
        "summary": "Comprehensive design intelligence for web and mobile UI/UX across multiple technology stacks.",
        "install_bash": npx_install("nextlevelbuilder/ui-ux-pro-max-skill", "ui-ux-pro-max"),
        "hub": "FAIL",
        "socket": "PASS",
        "snyk": "PASS",
    },
    {
        "file_slug": "brainstorming",
        "title": "brainstorming",
        "skill_page": "https://skills.sh/obra/superpowers/brainstorming",
        "repo": ("obra/superpowers", "https://github.com/obra/superpowers"),
        "session": "Yes",
        "weekly": "97.0K",
        "signal": "Success",
        "summary": "Structured brainstorming workflow before implementation (Obra Superpowers).",
        "install_bash": npx_install("obra/superpowers", "brainstorming"),
        "hub": "PASS",
        "socket": "PASS",
        "snyk": "PASS",
    },
    {
        "file_slug": "vercel-react-native-skills",
        "title": "vercel-react-native-skills",
        "skill_page": "https://skills.sh/vercel-labs/agent-skills/vercel-react-native-skills",
        "repo": ("vercel-labs/agent-skills", "https://github.com/vercel-labs/agent-skills"),
        "session": "Yes",
        "weekly": "85.9K",
        "signal": "Success",
        "summary": "React Native and Expo performance and architecture guidance from Vercel.",
        "install_bash": npx_install("vercel-labs/agent-skills", "vercel-react-native-skills"),
        "hub": "PASS",
        "socket": "PASS",
        "snyk": "PASS",
    },
    {
        "file_slug": "supabase-postgres-best-practices",
        "title": "supabase-postgres-best-practices",
        "skill_page": "https://skills.sh/supabase/agent-skills/supabase-postgres-best-practices",
        "repo": ("supabase/agent-skills", "https://github.com/supabase/agent-skills"),
        "session": "No",
        "weekly": "85.1K",
        "signal": "Success",
        "summary": "Postgres and Supabase-oriented best practices for agent-assisted development.",
        "install_bash": npx_install("supabase/agent-skills", "supabase-postgres-best-practices"),
        "hub": "PASS",
        "socket": "PASS",
        "snyk": "PASS",
    },
    {
        "file_slug": "next-best-practices",
        "title": "next-best-practices",
        "skill_page": "https://skills.sh/vercel-labs/next-skills/next-best-practices",
        "repo": ("vercel-labs/next-skills", "https://github.com/vercel-labs/next-skills"),
        "session": "No",
        "weekly": "58.9K",
        "signal": "Success",
        "summary": "Next.js best-practices skill from Vercel’s next-skills collection.",
        "install_bash": npx_install("vercel-labs/next-skills", "next-best-practices"),
        "hub": "PASS",
        "socket": "PASS",
        "snyk": "PASS",
    },
    {
        "file_slug": "shadcn",
        "title": "shadcn",
        "skill_page": "https://skills.sh/shadcn/ui/shadcn",
        "repo": ("shadcn/ui", "https://github.com/shadcn/ui"),
        "session": "Related: `shadcn-ui`",
        "weekly": "76.0K",
        "signal": "Review",
        "summary": "Complete shadcn/ui component management for adding, searching, fixing, styling, and composing UI.",
        "install_bash": npx_install("shadcn/ui", "shadcn"),
        "hub": "PASS",
        "socket": "PASS",
        "snyk": "WARN",
    },
    {
        "file_slug": "systematic-debugging",
        "title": "systematic-debugging",
        "skill_page": "https://skills.sh/obra/superpowers/systematic-debugging",
        "repo": ("obra/superpowers", "https://github.com/obra/superpowers"),
        "session": "No",
        "weekly": "54.8K",
        "signal": "Success",
        "summary": "Systematic debugging methodology (Obra Superpowers).",
        "install_bash": npx_install("obra/superpowers", "systematic-debugging"),
        "hub": "PASS",
        "socket": "PASS",
        "snyk": "PASS",
    },
    {
        "file_slug": "writing-plans",
        "title": "writing-plans",
        "skill_page": "https://skills.sh/obra/superpowers/writing-plans",
        "repo": ("obra/superpowers", "https://github.com/obra/superpowers"),
        "session": "Yes",
        "weekly": "53.8K",
        "signal": "Success",
        "summary": "Plan multi-step work with clear specs before implementation (Obra Superpowers).",
        "install_bash": npx_install("obra/superpowers", "writing-plans"),
        "hub": "PASS",
        "socket": "PASS",
        "snyk": "PASS",
    },
    {
        "file_slug": "audit-website",
        "title": "audit-website",
        "skill_page": "https://skills.sh/squirrelscan/skills/audit-website",
        "repo": ("squirrelscan/skills", "https://github.com/squirrelscan/skills"),
        "session": "No",
        "weekly": "43.9K",
        "signal": "Review",
        "summary": "Comprehensive website auditing across 230+ rules in 21 categories including SEO, performance, security, and accessibility.",
        "install_bash": npx_install("squirrelscan/skills", "audit-website"),
        "hub": "PASS",
        "socket": "PASS",
        "snyk": "WARN",
    },
    {
        "file_slug": "using-superpowers",
        "title": "using-superpowers",
        "skill_page": "https://skills.sh/obra/superpowers/using-superpowers",
        "repo": ("obra/superpowers", "https://github.com/obra/superpowers"),
        "session": "No",
        "weekly": "56.0K",
        "signal": "Review",
        "summary": "How to use the Obra Superpowers skill suite effectively (summary not fully exposed on the public page snapshot).",
        "install_bash": npx_install("obra/superpowers", "using-superpowers"),
        "hub": "PASS",
        "socket": "WARN",
        "snyk": "PASS",
    },
    {
        "file_slug": "content-strategy",
        "title": "content-strategy",
        "skill_page": "https://skills.sh/coreyhaines31/marketingskills/content-strategy",
        "repo": ("coreyhaines31/marketingskills", "https://github.com/coreyhaines31/marketingskills"),
        "session": "Yes",
        "weekly": "42.0K",
        "signal": "Review",
        "summary": "Plan searchable and shareable content that drives traffic, builds authority, and generates leads.",
        "install_bash": npx_install("coreyhaines31/marketingskills", "content-strategy"),
        "hub": "PASS",
        "socket": "PASS",
        "snyk": "WARN",
    },
    {
        "file_slug": "requesting-code-review",
        "title": "requesting-code-review",
        "skill_page": "https://skills.sh/obra/superpowers/requesting-code-review",
        "repo": ("obra/superpowers", "https://github.com/obra/superpowers"),
        "session": "No",
        "weekly": "45.3K",
        "signal": "Success",
        "summary": "Structured code-review requests for agent-assisted workflows (Obra Superpowers).",
        "install_bash": npx_install("obra/superpowers", "requesting-code-review"),
        "hub": "PASS",
        "socket": "PASS",
        "snyk": "PASS",
    },
    {
        "file_slug": "better-auth-best-practices",
        "title": "better-auth-best-practices",
        "skill_page": "https://skills.sh/better-auth/skills/better-auth-best-practices",
        "repo": ("better-auth/skills", "https://github.com/better-auth/skills"),
        "session": "No",
        "weekly": "35.1K",
        "signal": "Success",
        "summary": "Better Auth integration and security patterns for application auth.",
        "install_bash": npx_install("better-auth/skills", "better-auth-best-practices"),
        "hub": "PASS",
        "socket": "PASS",
        "snyk": "PASS",
    },
    {
        "file_slug": "subagent-driven-development",
        "title": "subagent-driven-development",
        "skill_page": "https://skills.sh/obra/superpowers/subagent-driven-development",
        "repo": ("obra/superpowers", "https://github.com/obra/superpowers"),
        "session": "No",
        "weekly": "39.1K",
        "signal": "Success",
        "summary": "Subagent-driven development workflows (Obra Superpowers).",
        "install_bash": npx_install("obra/superpowers", "subagent-driven-development"),
        "hub": "PASS",
        "socket": "PASS",
        "snyk": "PASS",
    },
    {
        "file_slug": "mcp-builder",
        "title": "mcp-builder",
        "skill_page": "https://skills.sh/anthropics/skills/mcp-builder",
        "repo": ("anthropics/skills", "https://github.com/anthropics/skills"),
        "session": "No",
        "weekly": "35.3K",
        "signal": "Review",
        "summary": "Guide for building high-quality MCP servers that connect LLMs to external services.",
        "install_bash": npx_install("anthropics/skills", "mcp-builder"),
        "hub": "PASS",
        "socket": "PASS",
        "snyk": "WARN",
    },
    {
        "file_slug": "verification-before-completion",
        "title": "verification-before-completion",
        "skill_page": "https://skills.sh/obra/superpowers/verification-before-completion",
        "repo": ("obra/superpowers", "https://github.com/obra/superpowers"),
        "session": "No",
        "weekly": "37.2K",
        "signal": "Success",
        "summary": "Verification gates before marking work complete (Obra Superpowers).",
        "install_bash": npx_install("obra/superpowers", "verification-before-completion"),
        "hub": "PASS",
        "socket": "PASS",
        "snyk": "PASS",
    },
    {
        "file_slug": "writing-skills",
        "title": "writing-skills",
        "skill_page": "https://skills.sh/obra/superpowers/writing-skills",
        "repo": ("obra/superpowers", "https://github.com/obra/superpowers"),
        "session": "No",
        "weekly": "36.1K",
        "signal": "Success",
        "summary": "Authoring and maintaining high-quality agent skills (Obra Superpowers).",
        "install_bash": npx_install("obra/superpowers", "writing-skills"),
        "hub": "PASS",
        "socket": "PASS",
        "snyk": "PASS",
    },
    {
        "file_slug": "using-git-worktrees",
        "title": "using-git-worktrees",
        "skill_page": "https://skills.sh/obra/superpowers/using-git-worktrees",
        "repo": ("obra/superpowers", "https://github.com/obra/superpowers"),
        "session": "No",
        "weekly": "34.5K",
        "signal": "Success",
        "summary": "Git worktree workflows for parallel agent sessions (Obra Superpowers).",
        "install_bash": npx_install("obra/superpowers", "using-git-worktrees"),
        "hub": "PASS",
        "socket": "PASS",
        "snyk": "PASS",
    },
    {
        "file_slug": "tailwind-design-system",
        "title": "tailwind-design-system",
        "skill_page": "https://skills.sh/wshobson/agents/tailwind-design-system",
        "repo": ("wshobson/agents", "https://github.com/wshobson/agents"),
        "session": "Yes",
        "weekly": "31.4K",
        "signal": "Success",
        "summary": "Tailwind CSS design systems, tokens, and scalable UI patterns.",
        "install_bash": npx_install("wshobson/agents", "tailwind-design-system"),
        "hub": "PASS",
        "socket": "PASS",
        "snyk": "PASS",
    },
    {
        "file_slug": "browser-use",
        "title": "browser-use",
        "skill_page": "https://skills.sh/browser-use/browser-use/browser-use",
        "repo": ("browser-use/browser-use", "https://github.com/browser-use/browser-use"),
        "session": "No",
        "weekly": "64.1K",
        "signal": "Danger",
        "summary": "Browser automation skill (see upstream repo and skill page for capabilities).",
        "install_bash": npx_install("browser-use/browser-use", "browser-use"),
        "hub": "WARN",
        "socket": "WARN",
        "snyk": "FAIL",
    },
    {
        "file_slug": "soultrace",
        "title": "soultrace",
        "skill_page": "https://skills.sh/soultrace-ai/soultrace-skill/soultrace",
        "repo": ("soultrace-ai/soultrace-skill", "https://github.com/soultrace-ai/soultrace-skill"),
        "session": "No",
        "weekly": "66.1K",
        "signal": "Review",
        "summary": "Soultrace skill (summary not fully exposed on the public page snapshot).",
        "install_bash": npx_install("soultrace-ai/soultrace-skill", "soultrace"),
        "hub": "PASS",
        "socket": "PASS",
        "snyk": "WARN",
    },
    {
        "file_slug": "secure-linux-web-hosting",
        "title": "secure-linux-web-hosting",
        "skill_page": "https://skills.sh/xixu-me/skills/secure-linux-web-hosting",
        "repo": ("xixu-me/skills", "https://github.com/xixu-me/skills"),
        "session": "No",
        "weekly": "50.2K",
        "signal": "Danger",
        "summary": "Secure Linux web hosting patterns (summary not fully exposed on the public page snapshot).",
        "install_bash": npx_install("xixu-me/skills", "secure-linux-web-hosting"),
        "hub": "FAIL",
        "socket": "PASS",
        "snyk": "WARN",
    },
    {
        "file_slug": "frontend-design-impeccable",
        "title": "frontend-design (pbakaus/impeccable)",
        "skill_page": "https://skills.sh/pbakaus/impeccable/frontend-design",
        "repo": ("pbakaus/impeccable", "https://github.com/pbakaus/impeccable"),
        "session": "Yes",
        "weekly": "53.2K",
        "signal": "Success",
        "summary": "Frontend design skill from pbakaus/impeccable (distinct listing from anthropics/skills; same CLI name — pick one upstream).",
        "install_bash": npx_install("pbakaus/impeccable", "frontend-design"),
        "hub": "PASS",
        "socket": "PASS",
        "snyk": "PASS",
    },
    {
        "file_slug": "critique",
        "title": "critique",
        "skill_page": "https://skills.sh/pbakaus/impeccable/critique",
        "repo": ("pbakaus/impeccable", "https://github.com/pbakaus/impeccable"),
        "session": "No",
        "weekly": "55.2K",
        "signal": "Success",
        "summary": "Critique and review workflows from the Impeccable skill set.",
        "install_bash": npx_install("pbakaus/impeccable", "critique"),
        "hub": "PASS",
        "socket": "PASS",
        "snyk": "PASS",
    },
    {
        "file_slug": "use-my-browser",
        "title": "use-my-browser",
        "skill_page": "https://skills.sh/xixu-me/skills/use-my-browser",
        "repo": ("xixu-me/skills", "https://github.com/xixu-me/skills"),
        "session": "No",
        "weekly": "47.7K",
        "signal": "Danger",
        "summary": "Browser-oriented skill from xixu-me/skills (summary not fully exposed on the public page snapshot).",
        "install_bash": npx_install("xixu-me/skills", "use-my-browser"),
        "hub": "FAIL",
        "socket": "PASS",
        "snyk": "WARN",
    },
    {
        "file_slug": "design-md",
        "title": "design-md",
        "skill_page": "https://skills.sh/google-labs-code/stitch-skills/design-md",
        "repo": ("google-labs-code/stitch-skills", "https://github.com/google-labs-code/stitch-skills"),
        "session": "No",
        "weekly": "32.3K",
        "signal": "Review",
        "summary": "Analyse Stitch design projects and generate semantic DESIGN.md files as a prompting source of truth.",
        "install_bash": npx_install("google-labs-code/stitch-skills", "design-md"),
        "hub": "PASS",
        "socket": "PASS",
        "snyk": "WARN",
    },
    {
        "file_slug": "brand-guidelines",
        "title": "brand-guidelines",
        "skill_page": "https://skills.sh/anthropics/skills/brand-guidelines",
        "repo": ("anthropics/skills", "https://github.com/anthropics/skills"),
        "session": "No",
        "weekly": "24.7K",
        "signal": "Success",
        "summary": "Brand guidelines authoring and enforcement for agent-assisted design.",
        "install_bash": npx_install("anthropics/skills", "brand-guidelines"),
        "hub": "PASS",
        "socket": "PASS",
        "snyk": "PASS",
    },
    {
        "file_slug": "shadcn-ui",
        "title": "shadcn-ui",
        "skill_page": "https://skills.sh/google-labs-code/stitch-skills/shadcn-ui",
        "repo": ("google-labs-code/stitch-skills", "https://github.com/google-labs-code/stitch-skills"),
        "session": "Yes",
        "weekly": "26.6K",
        "signal": "Review",
        "summary": "Discovering, installing, and customising shadcn/ui components (Stitch skills variant).",
        "install_bash": npx_install("google-labs-code/stitch-skills", "shadcn-ui"),
        "hub": "PASS",
        "socket": "PASS",
        "snyk": "WARN",
    },
    {
        "file_slug": "playwright-best-practices",
        "title": "playwright-best-practices",
        "skill_page": "https://skills.sh/currents-dev/playwright-best-practices-skill/playwright-best-practices",
        "repo": (
            "currents-dev/playwright-best-practices-skill",
            "https://github.com/currents-dev/playwright-best-practices-skill",
        ),
        "session": "No",
        "weekly": "24.1K",
        "signal": "Success",
        "summary": "Playwright testing best practices for agent-assisted automation.",
        "install_bash": npx_install(
            "currents-dev/playwright-best-practices-skill",
            "playwright-best-practices",
        ),
        "hub": "PASS",
        "socket": "PASS",
        "snyk": "PASS",
    },
    {
        "file_slug": "wordpress-router",
        "title": "wordpress-router",
        "skill_page": "https://skills.sh/wordpress/agent-skills/wordpress-router",
        "repo": ("WordPress/agent-skills", "https://github.com/WordPress/agent-skills"),
        "session": "No",
        "weekly": None,
        "signal": "Success",
        "summary": "Official WordPress organisation skill: routing context for WordPress projects (from [WordPress/agent-skills](https://github.com/WordPress/agent-skills)).",
        "install_bash": npx_install("WordPress/agent-skills", "wordpress-router"),
        "hub": "PASS",
        "socket": "PASS",
        "snyk": "PASS",
    },
    {
        "file_slug": "wp-rest-api",
        "title": "wp-rest-api",
        "skill_page": "https://skills.sh/wordpress/agent-skills/wp-rest-api",
        "repo": ("WordPress/agent-skills", "https://github.com/WordPress/agent-skills"),
        "session": "No",
        "weekly": None,
        "signal": "Success",
        "summary": "Official WordPress organisation skill: REST API usage and conventions for agents.",
        "install_bash": npx_install("WordPress/agent-skills", "wp-rest-api"),
        "hub": "PASS",
        "socket": "PASS",
        "snyk": "PASS",
    },
    {
        "file_slug": "wp-project-triage",
        "title": "wp-project-triage",
        "skill_page": "https://skills.sh/wordpress/agent-skills/wp-project-triage",
        "repo": ("WordPress/agent-skills", "https://github.com/WordPress/agent-skills"),
        "session": "No",
        "weekly": None,
        "signal": "Success",
        "summary": "Official WordPress organisation skill: triaging WordPress projects systematically.",
        "install_bash": npx_install("WordPress/agent-skills", "wp-project-triage"),
        "hub": "PASS",
        "socket": "PASS",
        "snyk": "PASS",
    },
    {
        "file_slug": "wp-wpcli-and-ops",
        "title": "wp-wpcli-and-ops",
        "skill_page": "https://skills.sh/wordpress/agent-skills/wp-wpcli-and-ops",
        "repo": ("WordPress/agent-skills", "https://github.com/WordPress/agent-skills"),
        "session": "No",
        "weekly": None,
        "signal": "Success",
        "summary": "Official WordPress organisation skill: WP-CLI and operational workflows.",
        "install_bash": npx_install("WordPress/agent-skills", "wp-wpcli-and-ops"),
        "hub": "PASS",
        "socket": "PASS",
        "snyk": "PASS",
    },
    {
        "file_slug": "wp-interactivity-api",
        "title": "wp-interactivity-api",
        "skill_page": "https://skills.sh/wordpress/agent-skills/wp-interactivity-api",
        "repo": ("WordPress/agent-skills", "https://github.com/WordPress/agent-skills"),
        "session": "No",
        "weekly": None,
        "signal": "Success",
        "summary": "Official WordPress organisation skill: Interactivity API patterns for modern WordPress front ends.",
        "install_bash": npx_install("WordPress/agent-skills", "wp-interactivity-api"),
        "hub": "PASS",
        "socket": "PASS",
        "snyk": "PASS",
    },
    {
        "file_slug": "wp-abilities-api",
        "title": "wp-abilities-api",
        "skill_page": "https://skills.sh/wordpress/agent-skills/wp-abilities-api",
        "repo": ("WordPress/agent-skills", "https://github.com/WordPress/agent-skills"),
        "session": "No",
        "weekly": None,
        "signal": "Success",
        "summary": "Official WordPress organisation skill: Abilities API usage for agent workflows.",
        "install_bash": npx_install("WordPress/agent-skills", "wp-abilities-api"),
        "hub": "PASS",
        "socket": "PASS",
        "snyk": "PASS",
    },
    {
        "file_slug": "continual-learning",
        "title": "continual-learning",
        "skill_page": "https://skills.sh/cursor/plugins/continual-learning",
        "repo": ("cursor/plugins", "https://github.com/cursor/plugins"),
        "session": "No",
        "weekly": "57 (skills.sh)",
        "signal": "Success",
        "summary": "Keep AGENTS.md current by delegating the memory update flow to one subagent (orchestration-only parent skill).",
        "install_bash": npx_install("cursor/plugins", "continual-learning"),
        "hub": "PASS",
        "socket": "PASS",
        "snyk": "PASS",
    },
    {
        "file_slug": "ralph-loop",
        "title": "ralph-loop",
        "skill_page": "https://skills.sh/cursor/plugins/ralph-loop",
        "repo": ("cursor/plugins", "https://github.com/cursor/plugins"),
        "session": "No",
        "weekly": "30 (skills.sh)",
        "signal": "Success",
        "summary": "Iterative Ralph loop: repeat the same task prompt each turn with visible prior work (uses `.cursor/ralph/` state).",
        "install_bash": npx_install("cursor/plugins", "ralph-loop"),
        "hub": "PASS",
        "socket": "PASS",
        "snyk": "PASS",
    },
    {
        "file_slug": "the-agent-skills-directory",
        "title": "The Agent Skills Directory",
        "skill_page": "https://skills.sh/",
        "repo": None,
        "session": "No",
        "weekly": None,
        "signal": "Info",
        "summary": "Public directory at skills.sh — browse and discover skills; not an installable package itself.",
        "install_bash": None,
        "hub": "—",
        "socket": "—",
        "snyk": "—",
    },
]


def main() -> None:
    for row in RECORDS:
        text = render(
            title=row["title"],
            skill_page=row["skill_page"],
            repo=row.get("repo"),
            session=row["session"],
            weekly=row.get("weekly"),
            signal=row["signal"],
            summary=row["summary"],
            install_bash=row.get("install_bash"),
            hub=row["hub"],
            socket=row["socket"],
            snyk=row["snyk"],
        )
        out = ROOT / f"{row['file_slug']}.md"
        out.write_text(text, encoding="utf-8")
        print(out)


if __name__ == "__main__":
    main()
